language: python
python:
  - 3.6.2

services:
  - docker
  - docker-compose

install:
  - docker-compose -f docker-compose-prod.yml build

script:
  - echo "test -> to be done"

deploy:
  provider: script
  script: bash docker_push
  on:
    all_branches: true