version: '3'
services:     
  back_production:
    image: grosnico72/socketgame:master
    build:
      context: .
      dockerfile: ./server/Dockerfile.prod
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./server/:/usr/src/app/
    command: npm start
