version: '3'
services:     
  back_production:
    build:
      context: .
      dockerfile: ./server/Dockerfile.prod
    ports:
      - "8081:8081"
    volumes:
      - ./server/:/usr/src/app/
    command: npm start
